language: generic
os: osx
osx_image: xcode9.2 # macOS Sierra (OS X 10.12)

env:
  XENV_SKIP=true

before_install:
  - brew update
  - brew unlink python

install:
  - xcode-select -p
  - sudo xcode-select --switch /Library/Developer/CommandLineTools/
  - brew install ansible

script:
  - travis_wait 50 ansible-playbook -vvvv setup.yml -i hosts

notifications:
  slack:
    secure: nVzzR1nzlwWJr7Hxvc4hPBHXo0sSlJkk1opJD2S0n3/EuW2Dha6amCxWcW0036/9efR6emxuYhFz6X9+6uhz6nu3hzSDN4Bye8ON+aRz1FK8YRvVGZ0Cy0uqBCHVFBAMxAuTzWv/v4A2SwaeUaCiZxHYWuqqMZH8zGq4F5xLnnLzMejOK8upZzepez9+gVGApMk3Lyt92zemhNNENx63Lxjx7M3E1yW75lSAMyNzPzUxaFQUjDrBG+wCSpyYMT95Pki5LCLhXCOojnNhdUMpdMmZ0yZYAKHwci5HCrl0et4kC3S4WxtRu4e+XcoiQ5BrWaQ532vNd7LDMaSJslM3+mzejo/h+KeJ8Jw0u6gtZsaPo9H30gNu6OAdfxGRRWu0GXXsHXhs6cTV64d7OlwkTsceWKRSgmg9L0+qcMWlr6iCHvBJrQ0eoNhkIRxwaZKLvLqFFz3gS/V6jKPQ1NCK0v8leDklG+luA4Kqh3wBTRp5af/aaoc7F8Tn5oJY9gCgiDQ2Iyhgf0dJ1jEXz4etmXNP/pkKk4f0uozneL3/6DsWHua0317Hn8SFx/vem6eB6YuP284jCt8/aRdLbqBSnZXHaNKqPerOnqzBxKz7bv/A9DMOr3v/DbWoXSIJovYHe+He1/Dix4yzwtI/0P0nhT0hUuVnqjLdI7XrS5l+XuA=
