---
- hosts: localhost
  connection: local
  vars:
    user_name: Tsukasa Nishiyama
    user_email: tukaelu82@gmail.com
    user_os_name: tuka
    github_user: tukaelu
    timezone: Asia/Tokyo
    ci_skip: "{{ lookup('env', 'CI_SKIP') }}"
  roles:
    - macos.settings
    - macos.homebrew
    - macos.brewcask
    - macos.fonts
    - macos.dotfiles
    - develop.fishshell
    - develop.anyenv
    - develop.php
    - develop.python
    - develop.ruby
    - infra.tools
