---
- hosts: localhost
  connection: local
  vars:
    user_name: Tsukasa Nishiyama
    user_email: me@ioapm.jp
    github_user: ioapm
    timezone: Asia/Tokyo
    xenv_skip: "{{ lookup('env', 'XENV_SKIP') }}"
  roles:
    - macos.settings
    - macos.homebrew
    - macos.brewcask
    - macos.fonts
    - develop.fishshell
    - develop.anyenv
    - develop.php
    - develop.python
    - develop.ruby
