---
- hosts: localhost
  connection: local
  vars:
    user_name: Tsukasa Nishiyama
    user_email: me@ioapm.jp
    github_user: ioapm
    timezone: Asia/Tokyo
  roles:
    - macos.settings
    - macos.homebrew
    - macos.brewcask
    - develop.anyenv
