- name: List installed versions
  shell: . ~/.bash_profile && phpenv versions
  register: installed_versions
  when:
    - ci_skip != "true"

- name: Install php
  shell: . ~/.bash_profile && phpenv install {{ item.version }}
  with_items: '{{ php_versions }}'
  when:
    - ci_skip != "true"
    - "installed_versions.stdout.find('{{ item.version }}') == -1"

- name: Set global php version
  shell: . ~/.bash_profile && phpenv global {{ item.version }}
  with_items: '{{ php_versions }}'
  when:
    - ci_skip != "true"
    - '{{ item.global | default(false) }}'
