- name: Export anyenv
  shell: eval "$(~/.anyenv/bin/anyenv init -)"

- name: List installed versions
  shell: rbenv versions
  register: installed_versions

- name: Installing ruby when not yet
  shell: rbenv install {{ item.version }}
  with_items: '{{ ruby_versions }}'
  when: "installed_versions.stdout.find('{{ item.version }}') == -1"

- name: Set global ruby version
  shell: rbenv global {{ item.version }}
  with_items: '{{ ruby_versions }}'
  when: '{{ item.global | default(false) }}'

- name: Install RubyGems for global
  shell: gem i {{ item }}
  with_items: '{{ install_global_gems }}'
