- name: Copy .gitignore
  template:
    src: gitignore.j2
    dest: /Users/{{ user_os_name }}/.gitignore

- name: Copy .gitignore_global
  copy:
    src: ../files/gitignore_global
    dest: /Users/{{ user_os_name }}/.gitignore_global
    mode: 0644
